### ISSUE TITLE
about:blank URIs reporting issues

### ISSUE THREAD

**Issue by ahecht** [HTTPSChecker/releases#19]
We routinely see issues reported for our sites where the Document URI is `about:blank` or (more commonly) just `about`. The blocked URIs don't appear to have anything to do with our sites. Any ideas where those are coming from?

**Comment by stilliard** [comment]
Hi @ahecht, thanks for reporting this. 
We currently block about & about:blank in the Blocked URIs as this appeared to be some browser extensions causing this so we set these to be blocked by default, but I'd not seen it appear in the Document URI before.
I assume these are also being caused by browser extensions too but I'll read into this now to find out and if they are I'll add them to our default ignored list.

**Comment by stilliard** [comment]
Hey again, we've had a look into this to try to get the document uri to return as about or about:blank but no luck. 
In multiple browsers we've tried embedding iframes set to about:blank into sites and then adding mixed content inside them, running sites inside iframe and doing the same and also with blank popups etc, but we still can't reproduce this. 
We'll keep an eye out for any causes but for now we'll block any reports with the document uri set to about or about:blank as they appear unactionable anyway. 
Hope this is ok with you.

**Comment by ahecht** [comment]
Yeah, that works. I can't think of why this would happen either, the URIs being blocked didn't seem to be relevant, and I can't think of what we could do about it. Thanks!

**Comment by stilliard** [comment]
No problem, it should now be blocking any new issues like this & I've also updated the default block list for a few similar cases I noticed from the logs.
Thanks for reporting this, let me know if you find anything else weird like this :+1:
