### ISSUE TITLE
Warn on password and credit card form fields that will trigger Chrome's new logic

### ISSUE THREAD

**Issue by ericlaw1979** [HTTPSChecker/releases#3]
Have you considered adding a scanner to flag HTTP pages that will be marked insecure by Chrome starting in January 2017 (ref: https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html)? 

This might be super-useful and should be pretty easy to code. (Do you run dynamic javascript when you crawl?) 

Thanks for any pointers!

**Comment by stilliard** [comment]
Hi @ericlaw1979 ,
Thanks for the suggestion, we currently report on forms that explicitly post to HTTP pages but not yet 100% as chrome will, but sure we can definitely add this in soon. 

Also we don't yet run dynamic javascript, but we crawl over the javascript files in order to try and work out if they might later call a HTTP resource. For now our solution to this is our HTTPS Reporter online tool which uses CSP reporting to detect anything on the page including javascript.

**Comment by stilliard** [comment]
Hi @ericlaw1979,
Just a quick update we will be adding in the check for password & credit card forms sent over HTTP into the desktop tool later this week. 
Thanks again for suggesting this.

**Comment by stilliard** [comment]
Hey @ericlaw1979 , 
We've now implemented this feature, thanks again for the suggestion. 
We have some other ideas and we'd value your input, if it's ok we will contact you via the email address you registered with.
