### ISSUE TITLE
HTTPSChecker crashes in a long run site scanning

### ISSUE THREAD

**Issue by walkstudio** [HTTPSChecker/releases#31]
Hi everybody there,

we are a large media company that holds a few magazine websites with a lot of pages and visits.
We also got a currently valid HTTPS-Checker's premium license, but we are facing now a very big issue, as it follows.

Despite a successfully ended test, held on early days of last August, for the desktop version of a website with over than 350,000 pages, in these days the same test never actually ended. 
HTTPS-Checker suddenly crashes near 150,000 - 190,000 scanned pages, after that it seems to freeze, as it's no more possible to interact with the app.

These kind of test are very expensive in time... it's a long run and usually takes a couple or a few days, so we have taken all necessary precautions to avoid unexpected interruptions, such as Windows updates, power supply breaks and so on. We also tried to run the test over a few different PCs, all of these runs on Windows 7 Pro edition.

Important notice: in all successfully and unsuccessfully tests held before for the same site, the overall issues result is near 1%, so for 350,000 pages, we'll currently expect near 3500 or less.

**Our current app version and notable settings are:**
version 2.3.0
mode: mixed content only
user-agent switcher: HTTPSChecker (default)
Use robots.txt file rules flag: true
No additional robots rules
Issue cap: 50.000
Page cap: unlimited
queue interval: 200 (default)
queue concurrency: 10 (default)
crawl timeout: 15 (default)
crawl bail time: 108000

Thanks in advance
Nicola Boccardi

**Comment by stilliard** [comment]
Hi Nicola,
Thanks for your report.

Often issues of frozen crashes like this happen due to the high memory usage from the app during long scans. 
Would you be able to run Performance Monitor along side while running the HTTPSChecker scan to see if this is the case?

Alternatively, I've just noticed your crawl bail time is fairly high currently. This is used to check when to kill the scan process if it appears to be still running when it's finished. I'd recommend settings this back down to 300 (5 minutes) or even lower down to 60 to see the scan finish quicker e.g. if it was unable to properly calculate the pages remaining. 

If this still does not help, we do have an errors log available in %USERPROFILE%\AppData\Roaming\httpschecker\ that may help diagnose the issue.

Also, to help speed up the test a bit you could try decreasing the queue interval & increasing the queue concurrency. 
As a test you could try the interval down to 50 and concurrency up to 30. 

I hope this helps.

**Comment by walkstudio** [comment]
Hi Andrew,

thanks for your prompt reply...
I'll try your tips... hope it works, so I'll report here.

Thanks for now.
Nick
