### ISSUE TITLE
False error: The SSL Certificate on your site has expired

### ISSUE THREAD

**Issue by MKJJJ** [HTTPSChecker/releases#33]
HTTPSChecker won't crawl any sites using Let's encrypt certificates. I get the error: "The SSL Certificate on your site has expired". This is absolutely not true. All certificates  are perfectly fine. This is a new issue. I've tested sites using these certificates for years without any problems.

**Comment by stilliard** [comment]
Hi @MKJJJ 

Apologies about this issue, we're working on a new version to fix this issue atm and should have something ready soon, sorry for the issue during this time. 

The issue is due to the Let's Encrypt root CA certificate which recently expired (ref https://github.com/electron/electron/issues/31212).

I'll update you as soon as the new update is out which will resolve issues with sites using Let's Encrypt.

Thank you.

**Comment by MKJJJ** [comment]
Hi Andrew,
excellent! Thank you very much for the prompt reply!

Mike

**Comment by stilliard** [comment]
Hi @MKJJJ 
Apologies for the delay on this. 
Our latest release 3.0 is now available & the app should auto start the update when you next open it.

If you run into any issues with the update or with the fix please let me know & thanks for reporting the issue.

**Comment by MKJJJ** [comment]
Everythings works like a charm again. Thank you very much for the fix.
