### ISSUE TITLE
Program crashes when running for a long time

### ISSUE THREAD

**Issue by parovi** [HTTPSChecker/releases#5]
Hi, I'm using the version PRO from HTTPS Checker Beta, and I have an issue on it:

I start a check on my computer (Windows 7) with this options:
**Issue Cap:** 50,000
**Only Run Mixed Content Checks:** true
**User Agent Switcher:** Desktop Windows Chrome
**Use Robots.txt File Rules:** true
**Additional Robots.txt Style Rules:** disallow: _.produkt-_

When it reaches about 3500 pages checked, it crashes (I tried 3 times, with the same result)

**Comment by james-mckinnon** [comment]
Hi @parovi ,

Thanks for getting in contact, sorry to hear that you're having some problems with the app. 
We're looking into this issue now and will let you know as soon as we know more. To help us investigate, could you provide us with the details of the CPU and RAM that you have in your computer as well as the URL that you were scanning when this occurred, if possible?

Thanks

**Comment by parovi** [comment]
Hi @james-mckinnon ,

![2016-10-14_09h47_29](https://cloud.githubusercontent.com/assets/7724204/19379630/3b298850-91f3-11e6-86f0-6043c83cecb5.png)

The URL cannot help you lot, because I'm running it on my local machine (local server)

Thx

**Comment by james-mckinnon** [comment]
Hi @parovi ,

Looking at the system specs you have we are confident that it isn't a memory or cpu issue. We're about to release (hopefully early next week) an update that will add the ability to see a log of all the errors that the crawler encounters while scanning a site, which should help to narrow down the issue.

I'll let you know as soon as it goes live.

Thanks

**Comment by parovi** [comment]
Nice, thx

**Comment by james-mckinnon** [comment]
Hey @parovi ,

We've just launched v1.4.0 which adds a few small fixes as well as a debug log. As we haven't been able to replicate the issue you are seeing, could you please let us know if this release solves the issue. If the issue still persists after the application has updated, could you please send us the debug log in a text document?

Thanks

**Comment by parovi** [comment]
Yes, I will do

**Comment by parovi** [comment]
Programm still crashes!
Where can I find the log? Because the debug log that is shown on the programm is gone after chash

**Comment by stilliard** [comment]
Hi @Sliknikim,

Sorry about this, we believe the issue was the app was trying to allocate too much memory which crawling some sites. We've fixed this by switching from in memory storage to a temp file that is automatically removed on close of the app. 

We are now releasing the new version 1.4.1 which should start to download & update automatically the next time you open the app. Once it's updated it should prompt you to restart the app to start the latest version. 

We've tested a site that reported the same issue ( #7 ) with the new version and it crawls well over 10,000+ pages now without issue and should continue to crawl the entire site for you. 

Please let us know if there's any further issues, thank you.

**Comment by stilliard** [comment]
Closing this issue for now, but please re-open if it's still not fixed for you, thank you.

**Comment by parovi** [comment]
Looks better now, thanks a lot
