### ISSUE TITLE
App quits after about 6300 items

### ISSUE THREAD

**Issue by Sliknikim** [HTTPSChecker/releases#7]
While running the tool on our site it just keeps crashing around after 6000 links it checks for.  No error message...just quits.

Here's my sys info:
![system](https://cloud.githubusercontent.com/assets/22990395/19615507/eb7b0a64-97b4-11e6-937d-326d58bdbfb0.JPG)

our website we're running the tool on: simplytoimpress.com

We do have the premium subscription. I have downloaded the latest version - 1.4

Please advise.

**Comment by james-mckinnon** [comment]
Hi @Sliknikim ,

Sorry we haven't got back to you sooner. We are aware of this issue and believe it is related to #5 . We're looking in to a fix and will update you as soon as we know more.

Thanks,

**Comment by Sliknikim** [comment]
I have some additional information that may help.  I caught a screenshot of the debug log just before it closed down again. Hope it helps.
![mcc https checker debugger](https://cloud.githubusercontent.com/assets/22990395/19667366/52ecb128-9a05-11e6-878b-1e63e9a88e03.JPG)

**Comment by stilliard** [comment]
Hi @Sliknikim,

Sorry about this, we believe the issue was the app was trying to allocate too much memory which crawling some sites. We've fixed this by switching from in memory storage to a temp file that is automatically removed on close of the app. 

We are now releasing the new version 1.4.1 which should start to download & update automatically the next time you open the app. Once it's updated it should prompt you to restart the app to start the latest version. 

We've tested your site with the new version and it crawls well over 10,000+ pages now without issue and should continue to crawl the entire site for you. 

Please let us know if there's any further issues, thank you.

**Comment by Sliknikim** [comment]
It appears the new build has fixed the issue.  I'm able to complete the crawl now.  Thank you!
